http:
  routers:
    ledssecure:
      middlewares:
        - "basic-auth"
      service: "leds"
      rule: "Host(`leds.domain.com`)"
      tls:
        certResolver: "default"
        domains:
          - main: "*.domain.com"
  
  services:
    leds:
      loadBalancer:
        servers:
          - url: "http://192.168.0.30:80"

  middlewares:
    basic-auth:
      basicAuth:
        users:
          - "username:$apr1$rWnB4DqU$pr7tUSkSAmWHbJU5A5hKc1"
    https-redirect:
      redirectscheme:
        scheme: "https"
        permanent: "true"
