http:
  routers:
    ledssecure:
      middlewares:
        - "basic-auth"
      service: "leds"
      rule: "Host(`leds.replace.me`)"
      tls:
        certResolver: "default"
        domains:
          - main: "*.replace.me"
    catchall:
      entryPoints:
        - "websecure"
      rule: "PathPrefix(`/`)"
      service: "unavailable"
      priority: 1
      tls:
        certResolver: "default"
  
  services:
    leds:
      loadBalancer:
        servers:
          - url: "http://192.168.0.30:80"
    unavailable:
      loadBalancer:
        servers: {}

  middlewares:
    basic-auth:
      basicAuth:
        users:
          - "username:$apr1$rWnB4DqU$pr7tUSkSAmWHbJU5A5hKc1"
    https-redirect:
      redirectscheme:
        scheme: "https"
        permanent: "true"
tls:
  certificates:
    - certfile: /etc/traefik/file_configs/wildcard-prod.domain.com.fullchain
      keyfile: /etc/traefik/file_configs/wildcard-prod.domain.com.key
