log:
  level: "ERROR"

accessLog:
  filters:
    statusCodes:
      - "500-511"

serversTransport:
  insecureSkipVerify: "true"

api:
  dashboard: "true"
  insecure: "true"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: "true"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: "true"
    exposedbydefault: "false"
  file:
    directory: "/etc/traefik/file_configs"
    watch: "true"

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
