log:
  level: "WARN"

serversTransport:
  insecureSkipVerify: "true"

api:
  dashboard: "true"
  insecure: "true"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: "true"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: "true"
    exposedbydefault: "false"
  file:
    directory: "/etc/traefik/file_configs"
    watch: "true"

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    entryPoint: "web"

certificatesResolvers:
  default:
    acme:
      dnsChallenge:
        provider: "namecheap"
        delayBeforeCheck: 0
      email: "insert.email@here.com"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      storage: "acme2.json"
